### ISSUE TITLE
'disable' setting type conflicts with SublimeLinter's default behavior

### ISSUE THREAD

**Issue by dandee** [SublimeLinter/SublimeLinter-gjslint#10]
I've got error while loading my project's settings:

```
'linters' > 'gjslint' > 'disable': '' is not of type 'boolean'
```

gjslint documentation states that `disable` expects "A comma-separated list of error codes to ignore" but the documentation for the framework http://www.sublimelinter.com/en/latest/linter_settings.html states that:

**disable**

Disables the linter.

My assumption is that `disable` should disable whole linter, deactivating the plugin.

**Comment by dandee** [comment]
Found out that `@disable` is the proper way to disable linters.

**Comment by kaste** [comment]
Hi :wave:!

I'm a bit confused now. In the original post you show an error message indicating that you're on the latest SublimeLinter version. The 'error' was that you probably set `"disable": ""` in one of the settings, but it must be `"disable": true` or `false`. 

The documentation for this linter here is wrong and must be updated, bc the global `disable` settings takes precedence over specific linter settings. 

But now I'm confused bc `@disable` is afaik not a thing we evaluate. This is the old name/setting for older SublimeLinter versions.

**Comment by braver** [comment]
There is no longer a need for the `disable` setting to filter out certain error codes, SL 4.9 has it natively. We should refactor it out here.
