### ISSUE TITLE
Can't understand how to use it in sublime

### ISSUE THREAD

**Issue by volodimirian** [SublimeLinter/SublimeLinter-gjslint#8]
Hi,
Could you please tell me how I can use it in my sublime?
Other linters has some shortcuts and show errors in strings of code for one file.
But for this package I can't find any short cut.

It would you great if you help me with it..
Looking forward for your answer 

Thanks,
Vladimir

**Comment by braver** [comment]
Did you ever get it to work?

**Comment by volodimirian** [comment]
Hi 2 years was gone. It is not actual for now. I am using vscode now for coding :) Thank you for your fast answer.
